// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using wedding_api.Data;
using wedding_api.Models;

namespace weddingapi.Migrations
{
    [DbContext(typeof(RsvpContext))]
    partial class RsvpContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("wedding_api.Models.Guest", b =>
                {
                    b.Property<int>("GuestId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GuestName");

                    b.Property<int>("MealSelection");

                    b.Property<int>("RsvpId");

                    b.HasKey("GuestId");

                    b.HasIndex("RsvpId");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("wedding_api.Models.Rsvp", b =>
                {
                    b.Property<int>("RsvpId")
                        .ValueGeneratedOnAdd();

                    b.HasKey("RsvpId");

                    b.ToTable("Rsvps");
                });

            modelBuilder.Entity("wedding_api.Models.Guest", b =>
                {
                    b.HasOne("wedding_api.Models.Rsvp", "Rsvp")
                        .WithMany("Guests")
                        .HasForeignKey("RsvpId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
